//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string REMEN_BEZOPASNOSTY = "remen_bezopasnosty";
        
        public const string RAZGON = "razgon";
        
        public const string POVOROT_PRAVO = "povorot_pravo";
        
        public const string POVOROT_LEVO = "povorot_levo";
        
        public const string TESTING = "testing";
    }
}
